### ISSUE TITLE
Failed line cropping in page_parser

### ISSUE THREAD

**Issue by michal-hradis** [DCGM/pero-ocr#2]
Line crop fails. Job saved at /mnt/matylda1/hradis/PERO/BUGS/a9ccd42b-9b26-40ae-9c3b-6e4d26c21ee0

Processing 4/24 (16.67 %) [id: b0a89e97-5c8a-4511-94db-7fed583bcba9]
Traceback (most recent call last):
  File "/home/ihradis/projects/2018-01-15_PERO/pero-ocr-live/user_scripts/parse_folder.py", line 172, in <module>
    main()
  File "/home/ihradis/projects/2018-01-15_PERO/pero-ocr-live/user_scripts/parse_folder.py", line 150, in main
    page_layout = page_parser.process_page(image, page_layout)
  File "/home/ihradis/projects/2018-01-15_PERO/pero-ocr-live/pero_ocr/document_ocr/page_parser.py", line 256, in process_page
    page_layout = self.line_cropper.process_page(image, page_layout)
  File "/home/ihradis/projects/2018-01-15_PERO/pero-ocr-live/pero_ocr/document_ocr/page_parser.py", line 201, in process_page
    line.crop = self.crop_engine.crop(img, line.baseline, line.heights)
  File "/home/ihradis/projects/2018-01-15_PERO/pero-ocr-live/pero_ocr/document_ocr/crop_engine.py", line 70, in crop
    line_crop = cv2.remap(img_crop, coords[:, :, 0], coords[:, :, 1], interpolation=cv2.INTER_LINEAR, borderMode=cv2.BORDER_TRANSPARENT)
cv2.error: OpenCV(4.0.0) /io/opencv/modules/imgproc/src/imgwarp.cpp:666: error: (-215:Assertion failed) !ssize.empty() in function 'remapBilinear'

**Comment by michal-hradis** [comment]
img_crop, coords, offset = self.get_crop_inputs(img, baseline, height)
returns img_crop.shape equal to (58, 0, 3)  
baseline:
[[2772.           -6.38325621]
 [2772.            0.        ]
 [2772.          108.        ]
 [2772.          216.        ]
 [2772.          324.        ]
 [2772.          432.        ]
 [2772.          540.        ]
 [2768.          648.        ]
 [2768.          756.        ]
 [2768.          864.        ]
 [2768.          972.        ]
 [2768.         1076.        ]
 [2768.         1091.        ]] 

heights:
[39.52720680236817, 14.290578651428223]

**Comment by michal-hradis** [comment]
I rewrote the cropping code. It should be nicer and faster. Original issue is fixed. 2dbad7a6453ce7456762f2a2f58483b31308d8d1
