### ISSUE TITLE
Can't install through pip

### ISSUE THREAD

**Issue by andrefpoliveira** [DCGM/pero-ocr#48]
Hi, I'm trying to use this repository in a college project, but I'm can't seem to do `pip install pero-ocr`.

I'm getting the following error
```
The conflict is caused by:
    pero-ocr 0.5 depends on tensorflow-gpu==1.15
    pero-ocr 0.4 depends on tensorflow-gpu==1.15
    pero-ocr 0.3 depends on tensorflow-gpu==1.15
    pero-ocr 0.2 depends on tensorflow-gpu==1.14
    pero-ocr 0.1.1 depends on tensorflow-gpu==1.14
```

But when trying to install that version of tensorflow-gpu, I can't seem to get a valid version.

Thank you.

**Comment by kohuthonza** [comment]
A new version without TensorFlow will be released on Friday.

**Comment by andrefpoliveira** [comment]
@kohuthonza is this new version on master? Or should I find it in another branch? Thank you!

**Comment by ibenes** [comment]
Hello @andrefpoliveira, I apologize for the delay, that's my fault. I have just push 0.6 onto master. Could you please check that it installs well for you (through setup.py)? I have had difficult time putting the dependencies together just right and if you are at it, I would like to get a confirmation of install-ability from another person before I push to PyPi.

Thanks for your patience and. in advance, for your input.

**Comment by andrefpoliveira** [comment]
Hey @ibenes. I had an error installing through `setup.py`. I'm trying to do this on Windows 10 if that helps

```
PS C:\Users\Andre.LAPTOP01\Desktop\pero-ocr> python .\setup.py install             
running install
C:\Users\Andre.LAPTOP01\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
C:\Users\Andre.LAPTOP01\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\command\easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
writing pero_ocr.egg-info\PKG-INFO
writing dependency_links to pero_ocr.egg-info\dependency_links.txt
writing requirements to pero_ocr.egg-info\requires.txt
writing top-level names to pero_ocr.egg-info\top_level.txt        
reading manifest file 'pero_ocr.egg-info\SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'pero_ocr.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg 
running install_lib
running build_py
creating build\bdist.win-amd64\egg
creating build\bdist.win-amd64\egg\pero_ocr
copying build\lib\pero_ocr\char_confidences.py -> build\bdist.win-amd64\egg\pero_ocr
copying build\lib\pero_ocr\confidence_estimation.py -> build\bdist.win-amd64\egg\pero_ocr
creating build\bdist.win-amd64\egg\pero_ocr\decoding
copying build\lib\pero_ocr\decoding\bag_of_hypotheses.py -> build\bdist.win-amd64\egg\pero_ocr\decoding 
copying build\lib\pero_ocr\decoding\confusion_networks.py -> build\bdist.win-amd64\egg\pero_ocr\decoding
copying build\lib\pero_ocr\decoding\decoders.py -> build\bdist.win-amd64\egg\pero_ocr\decoding
copying build\lib\pero_ocr\decoding\decoding_itf.py -> build\bdist.win-amd64\egg\pero_ocr\decoding      
copying build\lib\pero_ocr\decoding\lm_wrapper.py -> build\bdist.win-amd64\egg\pero_ocr\decoding        
copying build\lib\pero_ocr\decoding\multisort.py -> build\bdist.win-amd64\egg\pero_ocr\decoding
copying build\lib\pero_ocr\decoding\__init__.py -> build\bdist.win-amd64\egg\pero_ocr\decoding
creating build\bdist.win-amd64\egg\pero_ocr\document_ocr
copying build\lib\pero_ocr\document_ocr\arabic_helper.py -> build\bdist.win-amd64\egg\pero_ocr\document_ocr
copying build\lib\pero_ocr\document_ocr\crop_engine.py -> build\bdist.win-amd64\egg\pero_ocr\document_ocr
copying build\lib\pero_ocr\document_ocr\IO_utils.py -> build\bdist.win-amd64\egg\pero_ocr\document_ocr
copying build\lib\pero_ocr\document_ocr\layout.py -> build\bdist.win-amd64\egg\pero_ocr\document_ocr
copying build\lib\pero_ocr\document_ocr\page_parser.py -> build\bdist.win-amd64\egg\pero_ocr\document_ocr
copying build\lib\pero_ocr\document_ocr\__init__.py -> build\bdist.win-amd64\egg\pero_ocr\document_ocr
copying build\lib\pero_ocr\error_summary.py -> build\bdist.win-amd64\egg\pero_ocr
copying build\lib\pero_ocr\force_alignment.py -> build\bdist.win-amd64\egg\pero_ocr
creating build\bdist.win-amd64\egg\pero_ocr\layout_engines
copying build\lib\pero_ocr\layout_engines\baseline_refiner.py -> build\bdist.win-amd64\egg\pero_ocr\layout_engines
copying build\lib\pero_ocr\layout_engines\cnn_layout_engine.py -> build\bdist.win-amd64\egg\pero_ocr\layout_engines
copying build\lib\pero_ocr\layout_engines\layout_helpers.py -> build\bdist.win-amd64\egg\pero_ocr\layout_engines
copying build\lib\pero_ocr\layout_engines\line_in_region_detector.py -> build\bdist.win-amd64\egg\pero_ocr\layout_engines
copying build\lib\pero_ocr\layout_engines\line_postprocessing_engine.py -> build\bdist.win-amd64\egg\pero_ocr\layout_engines
copying build\lib\pero_ocr\layout_engines\naive_sorter.py -> build\bdist.win-amd64\egg\pero_ocr\layout_engines
copying build\lib\pero_ocr\layout_engines\simple_baseline_engine.py -> build\bdist.win-amd64\egg\pero_ocr\layout_engines
copying build\lib\pero_ocr\layout_engines\simple_region_engine.py -> build\bdist.win-amd64\egg\pero_ocr\layout_engines
copying build\lib\pero_ocr\layout_engines\smart_sorter.py -> build\bdist.win-amd64\egg\pero_ocr\layout_engines
copying build\lib\pero_ocr\layout_engines\torch_parsenet.py -> build\bdist.win-amd64\egg\pero_ocr\layout_engines
copying build\lib\pero_ocr\layout_engines\__init__.py -> build\bdist.win-amd64\egg\pero_ocr\layout_engines
copying build\lib\pero_ocr\line_images_io.py -> build\bdist.win-amd64\egg\pero_ocr
creating build\bdist.win-amd64\egg\pero_ocr\ocr_engine
copying build\lib\pero_ocr\ocr_engine\line_ocr_engine.py -> build\bdist.win-amd64\egg\pero_ocr\ocr_engine
copying build\lib\pero_ocr\ocr_engine\postprocess.py -> build\bdist.win-amd64\egg\pero_ocr\ocr_engine
copying build\lib\pero_ocr\ocr_engine\pytorch_ocr_engine.py -> build\bdist.win-amd64\egg\pero_ocr\ocr_engine
copying build\lib\pero_ocr\ocr_engine\softmax.py -> build\bdist.win-amd64\egg\pero_ocr\ocr_engine
copying build\lib\pero_ocr\ocr_engine\__init__.py -> build\bdist.win-amd64\egg\pero_ocr\ocr_engine
copying build\lib\pero_ocr\sequence_alignment.py -> build\bdist.win-amd64\egg\pero_ocr
copying build\lib\pero_ocr\transcription_io.py -> build\bdist.win-amd64\egg\pero_ocr
copying build\lib\pero_ocr\utils.py -> build\bdist.win-amd64\egg\pero_ocr
copying build\lib\pero_ocr\__init__.py -> build\bdist.win-amd64\egg\pero_ocr
byte-compiling build\bdist.win-amd64\egg\pero_ocr\char_confidences.py to char_confidences.cpython-310.pyc
byte-compiling build\bdist.win-amd64\egg\pero_ocr\confidence_estimation.py to confidence_estimation.cpython-310.pyc
byte-compiling build\bdist.win-amd64\egg\pero_ocr\decoding\bag_of_hypotheses.py to bag_of_hypotheses.cpython-310.pyc
byte-compiling build\bdist.win-amd64\egg\pero_ocr\decoding\confusion_networks.py to confusion_networks.cpython-310.pyc
byte-compiling build\bdist.win-amd64\egg\pero_ocr\decoding\decoders.py to decoders.cpython-310.pyc
byte-compiling build\bdist.win-amd64\egg\pero_ocr\decoding\decoding_itf.py to decoding_itf.cpython-310.pyc
byte-compiling build\bdist.win-amd64\egg\pero_ocr\decoding\lm_wrapper.py to lm_wrapper.cpython-310.pyc
byte-compiling build\bdist.win-amd64\egg\pero_ocr\decoding\multisort.py to multisort.cpython-310.pyc
byte-compiling build\bdist.win-amd64\egg\pero_ocr\decoding\__init__.py to __init__.cpython-310.pyc
byte-compiling build\bdist.win-amd64\egg\pero_ocr\document_ocr\arabic_helper.py to arabic_helper.cpython-310.pyc
byte-compiling build\bdist.win-amd64\egg\pero_ocr\document_ocr\crop_engine.py to crop_engine.cpython-310.pyc
byte-compiling build\bdist.win-amd64\egg\pero_ocr\document_ocr\IO_utils.py to IO_utils.cpython-310.pyc
byte-compiling build\bdist.win-amd64\egg\pero_ocr\document_ocr\layout.py to layout.cpython-310.pyc
byte-compiling build\bdist.win-amd64\egg\pero_ocr\document_ocr\page_parser.py to page_parser.cpython-310.pyc
byte-compiling build\bdist.win-amd64\egg\pero_ocr\document_ocr\__init__.py to __init__.cpython-310.pyc
byte-compiling build\bdist.win-amd64\egg\pero_ocr\error_summary.py to error_summary.cpython-310.pyc
byte-compiling build\bdist.win-amd64\egg\pero_ocr\force_alignment.py to force_alignment.cpython-310.pyc
byte-compiling build\bdist.win-amd64\egg\pero_ocr\layout_engines\baseline_refiner.py to baseline_refiner.cpython-310.pyc
byte-compiling build\bdist.win-amd64\egg\pero_ocr\layout_engines\cnn_layout_engine.py to cnn_layout_engine.cpython-310.pyc
byte-compiling build\bdist.win-amd64\egg\pero_ocr\layout_engines\layout_helpers.py to layout_helpers.cpython-310.pyc
byte-compiling build\bdist.win-amd64\egg\pero_ocr\layout_engines\line_in_region_detector.py to line_in_region_detector.cpython-310.pyc
byte-compiling build\bdist.win-amd64\egg\pero_ocr\layout_engines\line_postprocessing_engine.py to line_postprocessing_engine.cpython-310.pyc
byte-compiling build\bdist.win-amd64\egg\pero_ocr\layout_engines\naive_sorter.py to naive_sorter.cpython-310.pyc
byte-compiling build\bdist.win-amd64\egg\pero_ocr\layout_engines\simple_baseline_engine.py to simple_baseline_engine.cpython-310.pyc
byte-compiling build\bdist.win-amd64\egg\pero_ocr\layout_engines\simple_region_engine.py to simple_region_engine.cpython-310.pyc
byte-compiling build\bdist.win-amd64\egg\pero_ocr\layout_engines\smart_sorter.py to smart_sorter.cpython-310.pyc
byte-compiling build\bdist.win-amd64\egg\pero_ocr\layout_engines\torch_parsenet.py to torch_parsenet.cpython-310.pyc
byte-compiling build\bdist.win-amd64\egg\pero_ocr\layout_engines\__init__.py to __init__.cpython-310.pyc
byte-compiling build\bdist.win-amd64\egg\pero_ocr\line_images_io.py to line_images_io.cpython-310.pyc
byte-compiling build\bdist.win-amd64\egg\pero_ocr\ocr_engine\line_ocr_engine.py to line_ocr_engine.cpython-310.pyc
byte-compiling build\bdist.win-amd64\egg\pero_ocr\ocr_engine\postprocess.py to postprocess.cpython-310.pyc
byte-compiling build\bdist.win-amd64\egg\pero_ocr\ocr_engine\pytorch_ocr_engine.py to pytorch_ocr_engine.cpython-310.pyc
byte-compiling build\bdist.win-amd64\egg\pero_ocr\ocr_engine\softmax.py to softmax.cpython-310.pyc
byte-compiling build\bdist.win-amd64\egg\pero_ocr\ocr_engine\__init__.py to __init__.cpython-310.pyc
byte-compiling build\bdist.win-amd64\egg\pero_ocr\sequence_alignment.py to sequence_alignment.cpython-310.pyc
byte-compiling build\bdist.win-amd64\egg\pero_ocr\transcription_io.py to transcription_io.cpython-310.pyc
byte-compiling build\bdist.win-amd64\egg\pero_ocr\utils.py to utils.cpython-310.pyc
byte-compiling build\bdist.win-amd64\egg\pero_ocr\__init__.py to __init__.cpython-310.pyc
creating build\bdist.win-amd64\egg\EGG-INFO
copying pero_ocr.egg-info\PKG-INFO -> build\bdist.win-amd64\egg\EGG-INFO
copying pero_ocr.egg-info\SOURCES.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying pero_ocr.egg-info\dependency_links.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying pero_ocr.egg-info\requires.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying pero_ocr.egg-info\top_level.txt -> build\bdist.win-amd64\egg\EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist\pero_ocr-0.6.0-py3.10.egg' and adding 'build\bdist.win-amd64\egg' to it
removing 'build\bdist.win-amd64\egg' (and everything under it)
Processing pero_ocr-0.6.0-py3.10.egg
Removing c:\users\andre.laptop01\appdata\local\programs\python\python310\lib\site-packages\pero_ocr-0.6.0-py3.10.egg
error: [WinError 32] O processo não pode aceder ao ficheiro porque este está a ser utilizado por outro processo: 'c:\\users\\andre.laptop01\\appdata\\local\\programs\\python\\python310\\lib\\site-packages\\pero_ocr-0.6.0-py3.10.egg'
```

**Comment by andrefpoliveira** [comment]
@ibenes culd not replicate it no...

Throught pip I'm getting this error:
```
C:\Users\Andre.LAPTOP01>pip install pero-ocr
Collecting pero-ocr
  Using cached pero_ocr-0.6.0-py3-none-any.whl (73 kB)
Collecting lxml
  Using cached lxml-4.9.1-cp310-cp310-win_amd64.whl (3.6 MB)
Requirement already satisfied: torch>=1.12 in c:\users\andre.laptop01\appdata\local\programs\python\python310\lib\site-packages (from pero-ocr) (1.13.0)
Requirement already satisfied: numpy in c:\users\andre.laptop01\appdata\local\programs\python\python310\lib\site-packages (from pero-ocr) (1.23.4)
Requirement already satisfied: opencv-python in c:\users\andre.laptop01\appdata\local\programs\python\python310\lib\site-packages (from pero-ocr) (4.6.0.66)
Requirement already satisfied: pyamg in c:\users\andre.laptop01\appdata\local\programs\python\python310\lib\site-packages\pyamg-4.2.3-py3.10-win-amd64.egg (from pero-ocr) (4.2.3)
Requirement already satisfied: imgaug in c:\users\andre.laptop01\appdata\local\programs\python\python310\lib\site-packages\imgaug-0.4.0-py3.10.egg (from pero-ocr) (0.4.0)
Collecting numba
  Using cached numba-0.56.4-cp310-cp310-win_amd64.whl (2.5 MB)
Requirement already satisfied: scipy in c:\users\andre.laptop01\appdata\local\programs\python\python310\lib\site-packages (from pero-ocr) (1.9.3)
Requirement already satisfied: scikit-learn in c:\users\andre.laptop01\appdata\local\programs\python\python310\lib\site-packages (from pero-ocr) (1.1.2)
Collecting brnolm>=0.1.1
  Using cached brnolm-0.2.0-py3-none-any.whl (46 kB)
Requirement already satisfied: scikit-image in c:\users\andre.laptop01\appdata\local\programs\python\python310\lib\site-packages (from pero-ocr) (0.19.3)
Requirement already satisfied: arabic-reshaper in c:\users\andre.laptop01\appdata\local\programs\python\python310\lib\site-packages\arabic_reshaper-2.1.4-py3.10.egg (from pero-ocr) (2.1.4)
Requirement already satisfied: safe-gpu in c:\users\andre.laptop01\appdata\local\programs\python\python310\lib\site-packages\safe_gpu-1.4-py3.10.egg (from pero-ocr) (1.4)
Collecting shapely==1.8
  Using cached Shapely-1.8.0.tar.gz (278 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Andre.LAPTOP01\AppData\Local\Temp\pip-install-k90ddubb\shapely_3ffe1e3f8210412088ff206df8b42dea\setup.py", line 74, in <module>
          from shapely._buildcfg import geos_version_string, geos_version, \
        File "C:\Users\Andre.LAPTOP01\AppData\Local\Temp\pip-install-k90ddubb\shapely_3ffe1e3f8210412088ff206df8b42dea\shapely\_buildcfg.py", line 204, in <module>
          lgeos = CDLL("geos_c.dll")
        File "C:\Users\Andre.LAPTOP01\AppData\Local\Programs\Python\Python310\lib\ctypes\__init__.py", line 374, in __init__
          self._handle = _dlopen(self._name, mode)
      FileNotFoundError: Could not find module 'geos_c.dll' (or one of its dependencies). Try using the full path with constructor syntax.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Maybe there is a dependency missing?

**Comment by ibenes** [comment]
You are having an issue with installing `shapely`. I do not know the source of the issue, I have succesfully installed it on couple of systems just to check its version `1.8` was fine. I would kindly ask you to consult with them, this is beyond our control.
