### ISSUE TITLE
Line crop fails probably due empty mapping 

### ISSUE THREAD

**Issue by michal-hradis** [DCGM/pero-ocr#9]
Error log: 
 line_coords = self.get_crop_inputs(baseline, height, self.line_height)
Traceback (most recent call last):
  File "/home/pero/PERO/pero-ocr/user_scripts/parse_folder.py", line 176, in main
    page_layout = page_parser.process_page(image, page_layout)
  File "/home/pero/PERO/pero-ocr/pero_ocr/document_ocr/page_parser.py", line 408, in process_page
    page_layout = self.line_cropper.process_page(image, page_layout)
  File "/home/pero/PERO/pero-ocr/pero_ocr/document_ocr/page_parser.py", line 348, in process_page
    line.crop = self.crop_engine.crop(img, line.baseline, line.heights)
  File "/home/pero/PERO/pero-ocr/pero_ocr/document_ocr/crop_engine.py", line 78, in crop
    interpolation=cv2.INTER_LINEAR, borderMode=cv2.BORDER_CONSTANT)
cv2.error: OpenCV(4.2.0) /io/opencv/modules/imgproc/src/imgwarp.cpp:1703: error: (-215:Assertion failed) !_map1.empty() in function 'remap'

**Comment by michal-hradis** [comment]
I've added temporary fix. But we should look at it a bit more. I'll collect data for replication on monday.
